# mode = "server" #default: "server"

[trojan]
# listen = "127.0.0.1:443" #default: "0.0.0.0:443"
# password = ["password"] #default: None
fallback = "127.0.0.1:80" 

[tls]
sni = "example.com"
cert = "cert.pem"
key = "key.pem"

# [redis]  #default: None
# server = "localhost:5678"   #default: "localhost:5678"