# mode = "server" #default: "server"

[trojan]
# password = ["password"] #default: []
fallback = "127.0.0.1:80" 

[tls]
listen = "127.0.0.1:8888" #default: "0.0.0.0:443"
sni = "example.com"
cert = "fullchain.pem"
key = "privkey.pem"

# [redis]  #default: None
# server = "localhost:5678"   #default: "localhost:5678"